name: Update and Deploy
permissions:
  contents: read
  pages: write
  id-token: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build CSS
        run: npm run build-css

      - name: Update CSVs
        run: node scripts/update-csvs.js

      - name: Prepare Pages artifact
        run: |
          mkdir public
          rsync -av --exclude='.git' \
                    --exclude='.github' \
                    --exclude='README.md' \
                    --exclude='node_modules' \
                    --exclude='scripts' \
                    --exclude='input.css' \
                    --exclude='package.json' \
                    --exclude='package-lock.json' \
                    --exclude='tailwind.config.js' \
                    ./ ./public/      

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4