name: Update CSVs
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-each:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        csv:
          - name: ROBLOX
            gid: 0
          - name: MobileHD
            gid: 1165619838
          - name: Developer
            gid: 962693214
          - name: HangOutinaDiscoandChat
            gid: 1981780668
          - name: SpaceKnights
            gid: 816534120
          - name: SurviveTheDisasters
            gid: 2117257891
          - name: Internal
            gid: 1812577987

    outputs:
      changed: ${{ steps.detect.outputs.changed }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and compare CSV
        id: detect
        run: |
          name="${{ matrix.csv.name }}"
          gid="${{ matrix.csv.gid }}"
          url="https://docs.google.com/spreadsheets/d/1qAN8Eh4iPjO1aECiO1tclTXTLKfCka3StReywLJ3A58/export?format=csv&gid=$gid"
          target="csv/${name}.csv"

          curl -sL "$url" -o latest.csv

          if [ ! -f "$target" ] || ! cmp -s latest.csv "$target"; then
            echo "CSV changed for $name"
            mkdir -p out/csv
            mv latest.csv "out/${target}"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload changed file
        if: steps.detect.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: changed-${{ matrix.csv.name }}
          path: out/csv
          if-no-files-found: ignore

  commit-changes:
    needs: update-each
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all changed files
        uses: actions/download-artifact@v4
        with:
          pattern: changed-*
          path: csv
          merge-multiple: true

      - name: Commit and push
        run: |
          if git status --porcelain | grep .; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add csv/*.csv
            git commit -m "Update CSVs"
            git push
          else
            echo "No changes to commit"
          fi